allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  sharp: true
overrides:
  icu-minify@<=4.9.1: '>=4.9.2'
  nanoid@<3.3.16: '>=3.3.16'
  nanoid@<3.3.18: '>=3.3.18'
  next-intl@<=4.9.1: '>=4.9.2'
  next@>=10.0.0 <16.1.7: '>=16.1.7'
  next@>=16.0.0 <16.2.11: '>=16.2.11'
  next@>=16.0.0 <16.2.5: '>=16.2.5'
  next@>=16.0.0 <16.2.6: '>=16.2.6'
  next@>=16.0.0-beta.0 <16.1.7: '>=16.1.7'
  next@>=16.0.1 <16.1.7: '>=16.1.7'
  postcss@<8.5.10: '>=8.5.10'
  postcss@<=8.5.17: '>=8.5.18'
  postcss@<=8.5.22: '>=8.5.23'
  sharp@<0.35.0: '>=0.35.0'
